#!/usr/bin/env python3
"""
metadata_loader.py

Helpers to load TP metadata generated by generate_tp_metadata.py.

Exposes:
- load_tp_metadata(store_root, ne)
- list_nes_with_filter(store_root, required_category=None, required_role=None)
"""

import os
import json
from typing import Dict, Any, List, Optional


def _meta_path(store_root: str, ne: str) -> str:
    return os.path.join(store_root, f"NE={ne}", "tp_meta.json")


def load_tp_metadata(store_root: str, ne: str) -> Optional[Dict[str, Any]]:
    """
    Load tp_meta.json for a given NE.
    Returns dict or None if missing.
    """
    path = _meta_path(store_root, ne)
    if not os.path.isfile(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def list_all_nes(store_root: str) -> List[str]:
    if not os.path.isdir(store_root):
        return []
    return sorted(
        p.split("=", 1)[1]
        for p in os.listdir(store_root)
        if p.startswith("NE=")
    )


def list_nes_with_filter(
    store_root: str,
    required_category: Optional[str] = None,
    required_role: Optional[str] = None,
) -> List[str]:
    """
    Return list of NEs that have at least one TP matching
    the required category and/or role.
    """
    nes = list_all_nes(store_root)
    result = []

    for ne in nes:
        meta = load_tp_metadata(store_root, ne)
        if not meta:
            continue

        ok = False

        if required_category is None and required_role is None:
            ok = True
        else:
            # Check TPs one by one
            for tp, info in meta.get("tps", {}).items():
                cat = info.get("category")
                role = info.get("role")
                if required_category is not None and cat != required_category:
                    continue
                if required_role is not None and role != required_role:
                    continue
                ok = True
                break

        if ok:
            result.append(ne)

    return sorted(result)
